import { Bench } from "@/components/Bench";
import { AuthModal } from "@/components/sign-in/AuthModal";
import dynamic from "next/dynamic";
import Head from "next/head";
import { useState } from "react";

const DynamicInfiniteCanvas = dynamic(
  () => import("@/components/InfiniteCanvas"),
  {
    ssr: false,
  }
);

export default function Home() {
  const [showModal, setShowModal] = useState(true);

  return (
    <>
      <AuthModal setShowModal={setShowModal} />
      {!showModal ? (
        <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className="flex w-full h-full">
            <DynamicInfiniteCanvas />
            <div className="w-1/5 shrink-0" />
            <Bench />
          </div>
        </>
      ) : null}
    </>
  );
}
